services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: certificate-extractor-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
